sudo: required

language: java

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk8
    - jdk: oraclejdk9
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea
    
    script: mvn clean verify
