sudo: required

language: java

before_deploy:
   - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
   - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk8
    - jdk: oraclejdk9
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea
    
install:
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
## Build and release to maven central  
script: 
    mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
